#!/bin/sh
# File generated by ocamlbuild

cd /mnt/c/Users/merie/Desktop/WorkSpacesS2/WorkSpaceCA/CA/Projet_partie_2

rm -f ast.cmi
rm -f ast.cmo
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.ml
rm -f main.cmi
rm -f main.cmo
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
rm -f parser.mli
rm -f transformateur.cmi
rm -f transformateur.cmo
# Also clean the script itself
rm -f /mnt/c/Users/merie/Desktop/WorkSpacesS2/WorkSpaceCA/CA/Projet_partie_2/_build/sanitize.sh
